#!/usr/bin/env node
/**
 * gen_tool_docs.js — write docs/tools.md from the tool schemas.
 *
 *   node scripts/gen_tool_docs.js            rewrite docs/tools.md
 *   node scripts/gen_tool_docs.js --check    exit 1 if docs/tools.md is stale
 *
 * Every tool module under bots/agent/tools/ exports a factory that returns
 * tool definitions (name, description, input_schema, defaultInterrupts,
 * uninterruptible, parallelSafe). This script builds them with stub
 * dependencies (no bot, no server) and renders the schemas, plus the
 * failure reasons each module declares with fail('…') / partial('…').
 * Hand-written text lives in this file (PREAMBLE, MEMORY_TOOL) so the whole
 * document regenerates from one command: npm run docs.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { Nerves } from '../bots/agent/nerves.js';
import { INTERRUPT_SCHEMA } from '../bots/agent/tools/move.js';
import { perceiveTools } from '../bots/agent/tools/perceive.js';
import { moveTools } from '../bots/agent/tools/move.js';
import { escapeTools } from '../bots/agent/tools/escape.js';
import { gatherTools } from '../bots/agent/tools/gather.js';
import { jobTools } from '../bots/agent/tools/jobs.js';
import { buildTools } from '../bots/agent/tools/build.js';
import { farmTools } from '../bots/agent/tools/farm.js';
import { fightTools } from '../bots/agent/tools/fight.js';
import { socialTools } from '../bots/agent/tools/social.js';
import { boardTools } from '../bots/agent/tools/board.js';
import { factionTools } from '../bots/agent/tools/faction.js';
import { thinkTools } from '../bots/agent/tools/think.js';
import { scriptTools } from '../bots/agent/tools/script.js';
import { mindTools } from '../bots/agent/tools/mind.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const OUT = path.join(ROOT, 'docs', 'tools.md');
const TOOLS_DIR = path.join(ROOT, 'bots', 'agent', 'tools');

const GROUPS = [
  ['Perceive', 'perceive.js', perceiveTools, 'Read the world: position, surroundings, inventory, recipes. Instant and free.'],
  ['Move', 'move.js', moveTools, 'Pathfinding through the world substrate (bots/world/movement.js), doors included.'],
  ['Escape', 'escape.js', escapeTools, 'Get out of holes, water, fence tops and dark places; teleports with arrival checks.'],
  ['Gather', 'gather.js', gatherTools, 'Mining, crafting, smelting, placing, digging, equipment, eating, chests, drops, torches. Thin wrappers over bots/world/primitives.js.'],
  ['Jobs', 'jobs.js', jobTools, 'Long server-side work the bot does not have to stand next to: furnaces as jobs.'],
  ['Build', 'build.js', buildTools, 'Blueprints: list, survey a site, build (bots/building/).'],
  ['Farm', 'farm.js', farmTools, 'Plant, harvest and tend a farm plot.'],
  ['Fight', 'fight.js', fightTools, 'Combat through bots/world/combat.js.'],
  ['Social', 'social.js', socialTools, 'Chat and slash commands in the bot\'s voice.'],
  ['Board', 'board.js', boardTools, 'The economy and political picture through BotBridge queries.'],
  ['Faction', 'faction.js', factionTools, 'Massive Factions commands, selling and paying, the shared faction notes.'],
  ['Think', 'think.js', thinkTools, 'The strategist: a second model call that returns a memo.'],
  ['Scripts', 'script.js', scriptTools, 'Model-written JavaScript in a sandbox, and the saved-skill library (see docs/scripts-and-skills.md).'],
  ['Mind', 'mind.js', mindTools, 'Focus card, journal notes, waiting, logging off.'],
];

const PREAMBLE = `# Tools reference

*Generated by \`scripts/gen_tool_docs.js\` from the schemas in \`bots/agent/tools/\`;
run \`npm run docs\` after changing a tool. \`npm test\` fails when this file is stale.*

The agent plays Minecraft only through these tools. Each turn the model
receives the list below as the API's tool definitions, calls one or more,
and gets every result back as JSON. How the loop sequences calls, events
and interrupts is described in [agent-loop.md](agent-loop.md); how a tool
is implemented on top of the world substrate is in
[world-substrate.md](world-substrate.md).

## Result shape

Every tool answers with one JSON object (\`bots/agent/tools/result.js\`):

| Field | Meaning |
|---|---|
| \`status\` | \`ok\`, \`partial\` (something useful happened, then it stopped), \`failed\`, \`interrupted\` (an event pulled the bot out), \`unsupported\` |
| \`reason\` | a stable machine token for anything but plain \`ok\` (for example \`no_path\`, \`block_not_found\`, \`need_bucket\`); the per-group lists below are the tokens each module declares |
| \`by\`, \`detail\` | only with \`interrupted\`: the event that fired and what it carried (a damage event carries hp, amount, cause, attacker) |
| \`hint\` | free text telling the model what to try next, when the tool knows |
| \`elapsed_s\` | wall time |
| other fields | tool-specific: positions, counts, what was gained, what remains |

Tools never throw to the loop: an exception becomes \`failed\` with
\`reason: "exception:<message>"\` so the transcript stays truthful and the
model always gets its turn back.

## Interrupts

Actuators (anything that takes time) accept \`interrupt_on\`, a list of
events that end the call early: ${INTERRUPT_SCHEMA.items.enum.map((e) => `\`${e}\``).join(', ')}.
Each tool has a default (shown as *interrupts* below); pass \`[]\` to stay
heads-down. Lava, drowning and death always interrupt, and a few tools are
*uninterruptible* (only death or shutdown cancel them) so an escape finishes
before the model gets to reconsider. Interrupted calls report what was
achieved before the event, and the event itself is delivered to the model
with the result. Events that do not interrupt (\`dusk\`, \`dawn\`, \`job_done\`,
faction messages) arrive as \`[events]\` lines with the next turn.

Tools marked *parallel-safe* may be called in the same turn as other tools;
everything else runs one at a time in the order the model asked.
`;

const MEMORY_TOOL = `## Memory (\`memory\`)

Anthropic's memory tool (\`memory_20250818\`), backed by \`bots/agent/memoryTool.js\`
over \`data/memory/<bot>/\`. The model sees the API's built-in definition,
not a schema of ours; on Gemini the adapter exposes the same commands as an
ordinary function. Commands: \`view\`, \`create\`, \`str_replace\`, \`insert\`,
\`delete\`, \`rename\`, all under the virtual \`/memories\` directory. The
prompt asks the bot to keep \`plans.md\`, \`places.md\` and \`people.md\`;
\`note\` and \`logoff\` append to \`journal.md\`. The login bootstrap lists the
files. Errors come back as \`status: failed, reason: memory_error\` with the
store's message. *parallel-safe*
`;

function stubDeps() {
  const bot = {
    entity: { position: { x: 0, y: 64, z: 0 } }, inventory: { items: () => [], slots: [] }, players: {}, entities: {},
    on() {}, once() {}, off() {}, removeListener() {}, chat() {}, blockAt() { return null; },
  };
  return {
    bot, movement: {}, combat: null, perception: {}, registry: null, builder: null, memory: null, memoryStore: null,
    voice: { apply: (t) => t }, profile: { username: 'Doc', archetype: 'builder', skill_tier: 2, values: {}, voice: {}, spawn: { x: 0, y: 64, z: 0 } },
    log: null, nerves: new Nerves({ bot, username: 'Doc' }), state: { focus: null, stop: null, spawn: { x: 0, y: 64, z: 0 } },
    bus: null, factions: null, strategist: null, prices: null, factionRules: null, skillStore: null,
  };
}

const code = (s) => `\`${String(s).replace(/\|/g, '\\|')}\``;
const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const anchor = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

function typeOf(spec) {
  if (spec.enum) return `one of ${spec.enum.map(code).join(', ')}`;
  if (spec.type === 'array') {
    const it = spec.items ?? {};
    if (it.enum) return `array of ${it.enum.map(code).join(', ')}`;
    return `array of ${it.type ?? 'any'}`;
  }
  if (Array.isArray(spec.type)) return spec.type.join(' or ');
  return spec.type ?? 'any';
}
function constraintsOf(spec) {
  const c = [];
  if (spec.minimum != null) c.push(`min ${spec.minimum}`);
  if (spec.maximum != null) c.push(`max ${spec.maximum}`);
  if (spec.minLength != null) c.push(`min length ${spec.minLength}`);
  if (spec.maxLength != null) c.push(`max length ${spec.maxLength}`);
  if (spec.minItems != null) c.push(`min items ${spec.minItems}`);
  if (spec.maxItems != null) c.push(`max items ${spec.maxItems}`);
  return c.join(', ');
}
function firstSentence(text) {
  const t = String(text ?? '').replace(/\s+/g, ' ').trim();
  const m = /^(.{20,160}?[.!?])(\s|$)/.exec(t);
  return m ? m[1] : (t.length > 160 ? t.slice(0, 157) + '…' : t);
}

function reasonsIn(file) {
  const src = fs.readFileSync(path.join(TOOLS_DIR, file), 'utf8');
  const set = new Set();
  const re = /\b(?:fail|partial|unsupported)\(\s*'([a-z0-9_:]+)'/g;
  let m; while ((m = re.exec(src))) set.add(m[1]);
  return [...set].sort();
}

export function render() {
  const deps = stubDeps();
  const groups = GROUPS.map(([title, file, factory, blurb]) => ({ title, file, blurb, tools: factory(deps), reasons: reasonsIn(file) }));
  const out = [PREAMBLE];

  out.push('## All tools\n');
  out.push('| Tool | Group | Interrupts by default | What it does |');
  out.push('|---|---|---|---|');
  for (const g of groups) for (const t of g.tools) {
    const ints = t.uninterruptible ? '*uninterruptible*' : (t.defaultInterrupts?.length ? t.defaultInterrupts.map(code).join(' ') : 'none');
    out.push(`| [${code(t.name)}](#${anchor(t.name)}) | ${g.title} | ${ints} | ${cell(firstSentence(t.description))} |`);
  }
  out.push(`| ${code('memory')} | Memory | none | Anthropic's memory tool over data/memory/<bot>/ (see below). |`);
  out.push('');

  for (const g of groups) {
    out.push(`## ${g.title} (\`bots/agent/tools/${g.file}\`)\n`);
    out.push(`${g.blurb}\n`);
    for (const t of g.tools) {
      out.push(`### ${t.name}\n`);
      out.push(`${String(t.description).trim()}\n`);
      const schema = t.input_schema ?? {};
      const props = Object.entries(schema.properties ?? {});
      if (props.length) {
        out.push('| Input | Type | Constraints | Default | Required | Meaning |');
        out.push('|---|---|---|---|---|---|');
        for (const [k, spec] of props) {
          const req = (schema.required ?? []).includes(k) ? 'yes' : '';
          const def = spec.default !== undefined ? code(JSON.stringify(spec.default)) : '';
          out.push(`| ${code(k)} | ${cell(typeOf(spec))} | ${cell(constraintsOf(spec))} | ${def} | ${req} | ${cell(spec.description ?? '')} |`);
        }
      } else {
        out.push('No inputs.');
      }
      const flags = [];
      flags.push(t.uninterruptible ? '*uninterruptible*' : `*interrupts:* ${t.defaultInterrupts?.length ? t.defaultInterrupts.map(code).join(', ') : 'none by default'}`);
      if (t.parallelSafe) flags.push('*parallel-safe*');
      out.push(`\n${flags.join(' · ')}\n`);
    }
    if (g.reasons.length) {
      out.push(`**Failure reasons this module declares:** ${g.reasons.map(code).join(', ')}.\n`);
    }
  }
  out.push(MEMORY_TOOL);
  return out.join('\n');
}

export function run({ check = false } = {}) {
  const next = render();
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
  const stale = current !== next;
  if (check) return { file: path.relative(ROOT, OUT), stale };
  if (stale) { fs.mkdirSync(path.dirname(OUT), { recursive: true }); fs.writeFileSync(OUT, next); }
  return { file: path.relative(ROOT, OUT), stale, written: stale };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const check = process.argv.includes('--check');
  const r = run({ check });
  console.log(check ? `${r.file}: ${r.stale ? 'STALE (run npm run docs)' : 'up to date'}` : `${r.file}: ${r.written ? 'written' : 'unchanged'}`);
  process.exit(check && r.stale ? 1 : 0);
}
